---
# Main task file for Satellite host management operations
# Manages single node registration, host group operations, package updates, and compliance

- name: "Include Satellite connection validation tasks"
  include_tasks: validation.yml
  tags:
    - always

- name: "Include job template setup for host operations"
  include_tasks: job_templates.yml
  tags:
    - setup

# Single Node Operations
- name: "Perform single node registration and management"
  include_tasks: single_node.yml
  when:
    - target_hosts.single_node.hostname != ""
    - target_hosts.single_node.enabled | bool
  tags:
    - single-node

# Host Group Operations
- name: "Perform host group registration and management"
  include_tasks: host_groups.yml
  when:
    - target_hosts.host_groups | length > 0
    - target_hosts.host_groups[0].enabled | bool
  tags:
    - host-groups

# All Nodes Operations
- name: "Perform bulk operations on all nodes in organization"
  include_tasks: all_nodes.yml
  when:
    - target_hosts.all_nodes.enabled | bool
  tags:
    - all-nodes

# Package Update Operations
- name: "Perform CVE-specific package updates"
  include_tasks: cve_updates.yml
  when:
    - package_operations.cve_updates.enabled | bool
  tags:
    - cve-updates

- name: "Perform security and bugfix updates"
  include_tasks: security_bugfix_updates.yml
  when:
    - (package_operations.security_updates.enabled | bool) or 
      (package_operations.bugfix_updates.enabled | bool) or
      (package_operations.all_updates.enabled | bool)
  tags:
    - security-updates
    - bugfix-updates
    - all-updates

# Compliance Integration
- name: "Configure Red Hat Insights and RHC integration"
  include_tasks: insights_rhc_integration.yml
  when:
    - (insights_integration.install_client | bool) or 
      (rhc_integration.install_rhc | bool)
  tags:
    - compliance-integration

- name: "Generate comprehensive host management report"
  template:
    src: host_management_report.html.j2
    dest: "{{ playbook_dir }}/reports/satellite_host_management_{{ ansible_date_time.epoch }}.html"
  vars:
    report_timestamp: "{{ ansible_date_time.iso8601 }}"
    satellite_info:
      server: "{{ satellite_server_url }}"
      organization: "{{ satellite_organization }}"
      location: "{{ satellite_location }}"
    operation_summary:
      single_node_ops: "{{ target_hosts.single_node.enabled | bool }}"
      host_group_ops: "{{ target_hosts.host_groups | length > 0 and target_hosts.host_groups[0].enabled | bool }}"
      all_nodes_ops: "{{ target_hosts.all_nodes.enabled | bool }}"
      cve_updates: "{{ package_operations.cve_updates.enabled | bool }}"
      security_updates: "{{ package_operations.security_updates.enabled | bool }}"
      bugfix_updates: "{{ package_operations.bugfix_updates.enabled | bool }}"
      all_updates: "{{ package_operations.all_updates.enabled | bool }}"
      insights_integration: "{{ insights_integration.install_client | bool }}"
      rhc_integration: "{{ rhc_integration.install_rhc | bool }}"
  delegate_to: localhost
  run_once: true
  tags:
    - reporting

- name: "Display final host management summary"
  debug:
    msg:
      - "=============================================="
      - "Red Hat Satellite Host Management Complete"
      - "=============================================="
      - "Satellite Server: {{ satellite_server_url }}"
      - "Organization: {{ satellite_organization }}"
      - "Location: {{ satellite_location }}"
      - "Single Node Operations: {{ 'Enabled' if target_hosts.single_node.enabled | bool else 'Disabled' }}"
      - "Host Group Operations: {{ 'Enabled' if (target_hosts.host_groups | length > 0 and target_hosts.host_groups[0].enabled | bool) else 'Disabled' }}"
      - "All Nodes Operations: {{ 'Enabled' if target_hosts.all_nodes.enabled | bool else 'Disabled' }}"
      - "CVE Updates: {{ 'Completed' if package_operations.cve_updates.enabled | bool else 'Disabled' }}"
      - "Security Updates: {{ 'Completed' if package_operations.security_updates.enabled | bool else 'Disabled' }}"
      - "Bugfix Updates: {{ 'Completed' if package_operations.bugfix_updates.enabled | bool else 'Disabled' }}"
      - "Complete Updates: {{ 'Completed' if package_operations.all_updates.enabled | bool else 'Disabled' }}"
      - "Insights Integration: {{ 'Configured' if insights_integration.install_client | bool else 'Disabled' }}"
      - "RHC Integration: {{ 'Configured' if rhc_integration.install_rhc | bool else 'Disabled' }}"
      - "Reports Location: {{ playbook_dir }}/reports/"
      - "=============================================="
  run_once: true
  tags:
    - summary
# Author: sgallego
# Version: 2.0.0
# Date: 2025-08-27

- name: "Include validation tasks"
  include_tasks: validate.yml
  tags:
    - satellite-validation
    - always

- name: "Include single node registration"
  include_tasks: single_node.yml
  when: 
    - target_hosts.single_node.hostname != ""
    - target_hosts.single_node.activation_key != ""
  tags:
    - satellite-single-node
    - host-registration

- name: "Include host group registration"
  include_tasks: host_groups.yml
  when: 
    - target_hosts.host_groups is defined
    - target_hosts.host_groups | length > 0
  tags:
    - satellite-host-groups
    - host-registration

- name: "Include all nodes registration"
  include_tasks: all_nodes.yml
  when: 
    - target_hosts.all_nodes.activation_key != ""
    - bulk_operations.enabled | bool
  tags:
    - satellite-all-nodes
    - bulk-operations

- name: "Include CVE update management"
  include_tasks: cve_updates.yml
  when: package_operations.cve_updates.enabled | bool
  tags:
    - satellite-cve-updates
    - package-updates

- name: "Include security update management"
  include_tasks: security_updates.yml
  when: package_operations.security_updates.enabled | bool
  tags:
    - satellite-security-updates
    - package-updates

- name: "Include bugfix update management"
  include_tasks: bugfix_updates.yml
  when: package_operations.bugfix_updates.enabled | bool
  tags:
    - satellite-bugfix-updates
    - package-updates

- name: "Include all package updates"
  include_tasks: all_updates.yml
  when: package_operations.all_updates.enabled | bool
  tags:
    - satellite-all-updates
    - package-updates

- name: "Include insights and RHC configuration"
  include_tasks: insights_rhc.yml
  when: 
    - insights_config.auto_register | bool or rhc_config.auto_connect | bool
  tags:
    - satellite-insights
    - satellite-rhc
    - compliance

- name: "Include reporting and validation"
  include_tasks: reporting.yml
  when: generate_reports | bool
  tags:
    - satellite-reports
    - reporting
