---
galaxy_info:
  author: Orcun Atakan (oatakan@redhat.com) / Updated by ShaddGallegos
  description: Modern RHEL system update role with comprehensive package management, intelligent reboot handling, and enhanced error recovery across RHEL 7, 8, 9, and 10
  company: "Red Hat"
  license: "Apache-2.0"
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
        - 10
  galaxy_tags:
    - rhel
    - rhel7
    - rhel8
    - rhel9
    - rhel10
    - os
    - update
    - yum
    - dnf
    - patching
    - system
    - maintenance
    - reboot
    - packages

dependencies: []