---
patch_allow_downgrade: false
patch_apt_dist_upgrade: false
patch_auto_security: true
patch_backup_before: true
patch_cache_valid_time: 3600
patch_check_disk_space: true
patch_clean_cache: false
patch_create_snapshot: false
patch_critical_only: false
patch_download_only: false
patch_dry_run: false
patch_env: {}
patch_exclude: []
patch_generate_report: true
patch_install_timeout: 3600
patch_keep_kernel_versions: 3
patch_kernel_update: true
patch_log_directory: /var/log/ansible-patching
patch_log_updates: true
patch_min_disk_space_mb: 1024
patch_post_commands: []
patch_post_tasks: []
patch_pre_commands: []
patch_pre_tasks: []
patch_proxy_url: ''
patch_reboot: false
patch_reboot_delay: 60
patch_reboot_if_kernel: true
patch_reboot_timeout: 600
patch_report_format: json
patch_restart_services: []
patch_retries: 3
patch_retry_delay: 30
patch_security_only: false
patch_snapshot_name: pre-patch-{{ ansible_date_time.epoch }}
patch_start_services: []
patch_stop_services: []
patch_update_cache: true
patch_use_proxy: false
patch_validate_after: true
patch_validate_before: true
patch_yum_security_plugin: true
patch_zypper_no_recommends: false