---
# Reboot handling tasks

- name: Display pre-reboot message
  debug:
    msg: |
      Preparing to reboot system...
      Reason: {{ 'Kernel update' if update_rhel_kernel_reboot_needed | default(false) else 'System update' }}
      Pre-reboot delay: {{ update_rhel_pre_reboot_delay | default(10) }} seconds

- name: Wait before reboot (allow time for message display)
  pause:
    seconds: "{{ update_rhel_pre_reboot_delay | default(10) }}"
  when: update_rhel_pre_reboot_delay | default(10) > 0

- name: Reboot the system
  reboot:
    reboot_timeout: "{{ reboot_timeout | default(600) }}"
    connect_timeout: "{{ update_rhel_connect_timeout | default(10) }}"
    test_command: "{{ update_rhel_test_command | default('whoami') }}"
    pre_reboot_delay: 0  # We handled delay above
    post_reboot_delay: "{{ update_rhel_post_reboot_delay | default(30) }}"
  register: update_rhel_reboot_result

- name: Wait for system to be fully ready
  pause:
    seconds: "{{ update_rhel_post_reboot_delay | default(30) }}"
  when: update_rhel_post_reboot_delay | default(30) > 0

- name: Gather facts after reboot
  setup:
    filter: ansible_distribution*
  register: update_rhel_post_reboot_facts

- name: Update OS information after reboot
  set_fact:
    update_rhel_os_info_post_reboot:
      distribution: "{{ ansible_distribution }}"
      major_version: "{{ ansible_distribution_major_version|int }}"
      version: "{{ ansible_distribution_version }}"
      kernel: "{{ ansible_kernel }}"

- name: Verify reboot success
  debug:
    msg: |
      Reboot completed successfully!
      - System: {{ update_rhel_os_info_post_reboot.distribution }} {{ update_rhel_os_info_post_reboot.version }}
      - Current kernel: {{ update_rhel_os_info_post_reboot.kernel }}
      - Reboot duration: {{ update_rhel_reboot_result.elapsed }} seconds
  when: update_rhel_verbose | default(true)

- name: Verify kernel update success
  debug:
    msg: |
      Kernel update verification:
      {% if update_rhel_latest_kernel is defined and update_rhel_os_info_post_reboot.kernel == update_rhel_latest_kernel %}
      SUCCESS: Now running the latest kernel ({{ update_rhel_os_info_post_reboot.kernel }})
      {% elif update_rhel_latest_kernel is defined %}
      WARNING: Expected kernel {{ update_rhel_latest_kernel }}, but running {{ update_rhel_os_info_post_reboot.kernel }}
      {% else %}
      INFO: Kernel version after reboot: {{ update_rhel_os_info_post_reboot.kernel }}
      {% endif %}
  when: 
    - update_rhel_verbose | default(true)
    - update_rhel_kernel_reboot_needed | default(false)

- name: Run post-reboot validation commands
  command: "{{ item }}"
  loop: "{{ update_rhel_post_reboot_commands | default([]) }}"
  register: update_rhel_post_reboot_validation
  failed_when: false
  when: update_rhel_post_reboot_commands is defined

- name: Display post-reboot validation results
  debug:
    msg: |
      Post-reboot validation:
      {% for result in update_rhel_post_reboot_validation.results %}
      - Command: {{ result.item }}
      - Status: {{ 'PASS' if result.rc == 0 else 'FAIL' }}
      {% if result.stdout %}
      - Output: {{ result.stdout }}
      {% endif %}
      {% endfor %}
  when: 
    - update_rhel_post_reboot_validation is defined
    - update_rhel_verbose | default(true)

- name: Final reboot summary
  debug:
    msg: |
      Reboot Summary:
      - Reboot completed: {{ update_rhel_reboot_result.elapsed }} seconds
      - Pre-reboot kernel: {{ update_rhel_os_info.kernel }}
      - Post-reboot kernel: {{ update_rhel_os_info_post_reboot.kernel }}
      - Kernel update successful: {{ update_rhel_os_info_post_reboot.kernel == update_rhel_latest_kernel if update_rhel_latest_kernel is defined else 'N/A' }}
  when: update_rhel_verbose | default(true)
