---
# Satellite Repository Management - Validation Tasks
- name: "Validate Satellite server connectivity"
  uri:
  url: "https://{{ satellite_server_url }}/api/status"
  method: GET
  user: "{{ satellite_username }}"
  password: "{{ satellite_password }}"
  force_basic_auth: yes
  validate_certs: yes
  timeout: 30
  register: satellite_status
  failed_when: false
  tags:
  - validation

- name: "Display Satellite server status"
  debug:
  var: satellite_status.json
  when:
  - satellite_status.json is defined
  - debug_mode | bool
  tags:
  - validation

- name: "Fail if Satellite server is not accessible"
  fail:
  msg: "Cannot connect to Satellite server at {{ satellite_server_url }}"
  when: satellite_status.status != 200
  tags:
  - validation

- name: "Validate Red Hat credentials"
  fail:
  msg: "Red Hat credentials are required for repository management"
  when:
  - redhat_username == "" or redhat_username is not defined
  - redhat_password == "" or redhat_password is not defined
  - redhat_activation_key == "" or redhat_activation_key is not defined
  tags:
  - validation

- name: "Check organization exists"
  uri:
  url: "https://{{ satellite_server_url }}/katello/api/organizations"
  method: GET
  user: "{{ satellite_username }}"
  password: "{{ satellite_password }}"
  force_basic_auth: yes
  validate_certs: yes
  register: organizations
  tags:
  - validation

- name: "Extract organization ID"
  set_fact:
  organization_id: "{{ organizations.json.results | selectattr('name', 'equalto', satellite_organization) | map(attribute='id') | first }}"
  when: organizations.json.results | selectattr('name', 'equalto', satellite_organization) | list | length > 0
  tags:
  - validation

- name: "Fail if organization not found"
  fail:
  msg: "Organization '{{ satellite_organization }}' not found in Satellite"
  when: organization_id is not defined
  tags:
  - validation

- name: "Display validation results"
  debug:
  msg:
  - "Satellite server: {{ satellite_server_url }} - Status: OK"
  - "Organization: {{ satellite_organization }} (ID: {{ organization_id }})"
  - "RHEL Version: {{ rhel_version }}"
  - "Architecture: {{ rhel_architecture }}"
  tags:
  - validation
