---
- name: Include pre-report preparation tasks
  ansible.builtin.include_tasks: pre_report.yml

- name: Include system data collection tasks
  ansible.builtin.include_tasks: collect_data.yml

- name: Include report generation tasks
  ansible.builtin.include_tasks: generate_reports.yml

- name: Include report delivery tasks
  ansible.builtin.include_tasks: deliver_reports.yml