---
# Example playbook demonstrating comprehensive Red Hat Satellite 6.17 management
# This playbook showcases all three Satellite roles working together
# Usage: ansible-playbook -i inventory satellite_complete_demo.yml

- name: "Complete Red Hat Satellite 6.17 Management Demo"
  hosts: localhost
  become: false
  gather_facts: yes
  
  vars:
    # Satellite Server Configuration
    satellite_server_url: "https://satellite.example.com"
    satellite_username: "admin"
    satellite_password: "{{ vault_satellite_password | default('NTY4NjIw') }}"
    satellite_organization: "Default Organization"
    satellite_location: "Default Location"
    
    # Operation Mode
    dry_run: false
    debug_mode: true
    
    # Reports Directory
    reports_directory: "./reports"

  pre_tasks:
    - name: "Create reports directory"
      file:
        path: "{{ reports_directory }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: "Display demo banner"
      debug:
        msg:
          - "=============================================="
          - "Red Hat Satellite 6.17 Complete Management Demo"
          - "=============================================="
          - " Organization: {{ satellite_organization }}"
          - " Location: {{ satellite_location }}"
          - "  Satellite Server: {{ satellite_server_url }}"
          - " Ansible Platform: 2.5"
          - " Debug Mode: {{ debug_mode | bool }}"
          - " Dry Run: {{ dry_run | bool }}"
          - "=============================================="

  roles:
    # Phase 1: Repository Management - Set up Red Hat repos and sync plans
    - role: satellite-repository-management
      vars:
        # Repository Configuration
        red_hat_repositories:
          enable_cdn_repos: true
          rhel_9_repos:
            - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)"
              relative_path: "rhel-9-for-x86_64-baseos-rpms"
              content_type: "yum"
            - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)" 
              relative_path: "rhel-9-for-x86_64-appstream-rpms"
              content_type: "yum"
            - name: "Red Hat Enterprise Linux 9 for x86_64 - Supplementary (RPMs)"
              relative_path: "rhel-9-for-x86_64-supplementary-rpms"
              content_type: "yum"
            - name: "Red Hat Satellite 6.17 for RHEL 9 x86_64 (RPMs)"
              relative_path: "satellite-6.17-for-rhel-9-x86_64-rpms"
              content_type: "yum"
            - name: "Red Hat Satellite Maintenance 6.17 for RHEL 9 x86_64 (RPMs)"
              relative_path: "satellite-maintenance-6.17-for-rhel-9-x86_64-rpms"
              content_type: "yum"
        
        # Sync Plans by Product
        sync_plans:
          rhel_sync:
            name: "RHEL 9 Sync Plan"
            description: "Daily sync for RHEL 9 repositories"
            interval: "daily"
            sync_date: "2025-01-01 02:00:00 UTC"
            enabled: true
          satellite_sync:
            name: "Satellite 6.17 Sync Plan"
            description: "Weekly sync for Satellite repositories"
            interval: "weekly"
            sync_date: "2025-01-01 01:00:00 UTC"
            enabled: true
      tags:
        - repository-management

    # Phase 2: Content Lifecycle - Create environments, content views, activation keys
    - role: satellite-content-lifecycle
      vars:
        # Lifecycle Environments
        lifecycle_environments:
          dev:
            name: "RHEL_9_DEV_x86_64"
            description: "Development environment for RHEL 9"
            prior: "Library"
          test:
            name: "RHEL_9_TEST_x86_64"
            description: "Testing environment for RHEL 9"
            prior: "RHEL_9_DEV_x86_64"
          prod:
            name: "RHEL_9_PROD_x86_64"
            description: "Production environment for RHEL 9"
            prior: "RHEL_9_TEST_x86_64"
        
        # Content Views Configuration
        content_views:
          rhel_9_cv:
            name: "RHEL_9_Content_View"
            description: "RHEL 9 content view with dependency solving"
            auto_publish: true
            solve_dependencies: true
            repositories:
              - "Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)"
              - "Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)"
              - "Red Hat Enterprise Linux 9 for x86_64 - Supplementary (RPMs)"
          satellite_cv:
            name: "Satellite_6_17_Content_View"
            description: "Satellite 6.17 content view"
            auto_publish: true
            solve_dependencies: true
            repositories:
              - "Red Hat Satellite 6.17 for RHEL 9 x86_64 (RPMs)"
              - "Red Hat Satellite Maintenance 6.17 for RHEL 9 x86_64 (RPMs)"
        
        # Composite Content View
        composite_content_view:
          name: "RHEL_9-composite"
          description: "Composite content view for complete RHEL 9 stack"
          auto_publish: true
          component_content_views:
            - "RHEL_9_Content_View"
            - "Satellite_6_17_Content_View"
        
        # Activation Keys
        activation_keys:
          dev_key:
            name: "RHEL_9_DEV_x86_64_Key"
            lifecycle_environment: "RHEL_9_DEV_x86_64"
            content_view: "RHEL_9-composite"
            auto_attach: true
          test_key:
            name: "RHEL_9_TEST_x86_64_Key"
            lifecycle_environment: "RHEL_9_TEST_x86_64"
            content_view: "RHEL_9-composite"
            auto_attach: true
          prod_key:
            name: "RHEL_9_PROD_x86_64_Key"
            lifecycle_environment: "RHEL_9_PROD_x86_64"
            content_view: "RHEL_9-composite"
            auto_attach: true
        
        # Host Collections
        host_collections:
          dev_collection:
            name: "RHEL_9_Development_Hosts"
            description: "Development environment hosts"
          test_collection:
            name: "RHEL_9_Testing_Hosts"
            description: "Testing environment hosts"
          prod_collection:
            name: "RHEL_9_Production_Hosts"
            description: "Production environment hosts"
      tags:
        - content-lifecycle

    # Phase 3: Host Management - Register hosts, perform updates, configure compliance
    - role: satellite-host-management
      vars:
        # Target Hosts Configuration
        target_hosts:
          single_node:
            enabled: true
            hostname: "rhel9-demo-01.example.com"
            activation_key: "RHEL_9_PROD_x86_64_Key"
            host_collection: "RHEL_9_Production_Hosts"
            lifecycle_environment: "RHEL_9_PROD_x86_64"
          host_groups:
            - name: "RHEL_9_Production_Servers"
              enabled: true
              activation_key: "RHEL_9_PROD_x86_64_Key"
              host_collection: "RHEL_9_Production_Hosts"
              lifecycle_environment: "RHEL_9_PROD_x86_64"
          all_nodes:
            enabled: false  # Enable for organization-wide operations
        
        # Package Update Operations
        package_operations:
          cve_updates:
            enabled: true
            target_cves:
              - "CVE-2024-6387"  # OpenSSH vulnerability
              - "CVE-2024-1086"  # Kernel privilege escalation
              - "CVE-2023-4911"  # glibc buffer overflow
              - "CVE-2023-2002"  # Bluetooth vulnerability
              - "CVE-2023-32629" # GStreamer vulnerability
          security_updates:
            enabled: true
            update_type: "security"
          bugfix_updates:
            enabled: true
            update_type: "bugfix"
          all_updates:
            enabled: false  # Enable for complete system updates
          reboot_if_required: true
        
        # Job Configuration
        update_jobs:
          concurrency_level: 5
          timeout: 3600  # 1 hour
          reboot_delay_minutes: 5
        
        # Red Hat Insights Integration
        insights_integration:
          install_client: true
          register_hosts: true
          enable_data_collection: true
          compliance_reporting: true
        
        # Red Hat Connector Integration
        rhc_integration:
          install_rhc: true
          configure_connection: true
          enable_remote_management: true
          cloud_integration: true
      tags:
        - host-management

  post_tasks:
    - name: "Generate complete demo summary report"
      template:
        src: "{{ playbook_dir }}/templates/complete_demo_report.html.j2"
        dest: "{{ reports_directory }}/satellite_complete_demo_{{ ansible_date_time.epoch }}.html"
      vars:
        demo_summary:
          timestamp: "{{ ansible_date_time.iso8601 }}"
          satellite_server: "{{ satellite_server_url }}"
          organization: "{{ satellite_organization }}"
          location: "{{ satellite_location }}"
          phases_completed:
            repository_management: true
            content_lifecycle: true
            host_management: true
          operation_counts:
            repositories_enabled: 5
            lifecycle_environments_created: 3
            content_views_created: 3
            activation_keys_created: 3
            host_collections_created: 3
            update_operations_performed: "{{ [package_operations.cve_updates.enabled, package_operations.security_updates.enabled, package_operations.bugfix_updates.enabled, package_operations.all_updates.enabled] | select('equalto', true) | list | length }}"
            compliance_integrations: "{{ [insights_integration.install_client, rhc_integration.install_rhc] | select('equalto', true) | list | length }}"
      delegate_to: localhost
      run_once: true
      tags:
        - reporting

    - name: "Display complete demo results"
      debug:
        msg:
          - "=============================================="
          - " Red Hat Satellite 6.17 Demo Complete! "
          - "=============================================="
          - " Phase 1: Repository Management - COMPLETED"
          - "    5 RHEL 9 repositories enabled"
          - "    2 sync plans created and activated"
          - " Phase 2: Content Lifecycle - COMPLETED"
          - "     3 lifecycle environments created"
          - "    3 content views with dependency solving"
          - "    1 composite content view with auto-publish"
          - "    3 activation keys generated"
          - "    3 host collections configured"
          - " Phase 3: Host Management - COMPLETED"
          - "     Host registration and management"
          - "    CVE and security updates"
          - "    Insights and RHC integration"
          - " Reports: {{ reports_directory }}/"
          - "=============================================="
      run_once: true
      tags:
        - summary
