---
- name: System Update & Reporting Survey
  hosts: localhost
  gather_facts: true
  vars:
    run_inventory_report: "{{ survey_run_inventory_report }}"
    apply_security_updates: "{{ survey_apply_security_updates }}"
    apply_bugfix_updates: "{{ survey_apply_bugfix_updates }}"
    apply_enhancement_updates: "{{ survey_apply_enhancement_updates }}"
    apply_all_updates: "{{ survey_apply_all_updates }}"

  roles:
    - role: simple_report
      vars:
        simple_report_run_inventory_report: "{{ simple_report_run_inventory_report }}"
        simple_report_apply_security_updates: "{{ simple_report_apply_security_updates }}"
        simple_report_apply_bugfix_updates: "{{ simple_report_apply_bugfix_updates }}"
        simple_report_apply_enhancement_updates: "{{ simple_report_apply_enhancement_updates }}"
        simple_report_apply_all_updates: "{{ simple_report_apply_all_updates }}"
