---
- name: Universal System Updates Management
  hosts: all
  gather_facts: true
  vars:
    # Update configuration
    apply_security_updates: true
    apply_critical_updates: true
    auto_reboot: false
    generate_reports: true
    
  tasks:
    - name: Update Linux systems
      include_role:
        name: ansible-role-patching
      vars:
        patching_security_only: "{{ apply_security_updates }}"
        patching_reboot: "{{ auto_reboot }}"
        patching_generate_report: "{{ generate_reports }}"
      when: ansible_facts['os_family'] != "Windows"
      
    - name: Update Windows systems  
      include_role:
        name: ansible-role-win_updates-master
      vars:
        win_updates_category_names:
          - SecurityUpdates
          - CriticalUpdates
        win_updates_reboot: "{{ auto_reboot }}"
        win_updates_generate_report: "{{ generate_reports }}"
      when: ansible_facts['os_family'] == "Windows"
      
    - name: Generate consolidated report
      include_role:
        name: simple_report
      vars:
        simple_report_collect_all_hosts: true
        simple_report_format: 
          - html
          - json
      when: generate_reports | bool
