---
'10': true
'7': false
'8': true
'9': true
_yum_cache_dirs: null
_yum_config_files: null
_yum_default_installonly_limits: null
_yum_default_timeouts: null
_yum_features: null
_yum_log_files: null
_yum_package_managers: null
_yum_service_names: null
best: null
clean_requirements_on_remove: null
countme: null
fastestmirror: null
localpkg_gpgcheck: null
module_hotfixes: null
protect_running_kernel: null
zchunk: null