galaxy_info:
  author: David Norman
  description: Install Windows updates.
  license: BSD
  min_ansible_version: 2.0
  platforms:
  - name: Windows
    versions:
    - all
  galaxy_tags:
    - windows
    - security

dependencies: []
