---
# Content Lifecycle Validation Tasks

- name: "Validate Satellite connectivity"
  uri:
    url: "https://{{ satellite_server_url }}/api/status"
    method: GET
    user: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    force_basic_auth: yes
    validate_certs: yes
    timeout: 30
  register: satellite_status
  failed_when: satellite_status.status != 200
  tags:
    - validation

- name: "Get organization information"
  uri:
    url: "https://{{ satellite_server_url }}/katello/api/organizations"
    method: GET
    user: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    force_basic_auth: yes
    validate_certs: yes
  register: organizations
  tags:
    - validation

- name: "Extract organization ID"
  set_fact:
    organization_id: "{{ organizations.json.results | selectattr('name', 'equalto', satellite_organization) | map(attribute='id') | first }}"
  when: organizations.json.results | selectattr('name', 'equalto', satellite_organization) | list | length > 0
  tags:
    - validation

- name: "Validate organization exists"
  fail:
    msg: "Organization '{{ satellite_organization }}' not found"
  when: organization_id is not defined
  tags:
    - validation

- name: "Get existing repositories"
  uri:
    url: "https://{{ satellite_server_url }}/katello/api/organizations/{{ organization_id }}/repositories"
    method: GET
    user: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    force_basic_auth: yes
    validate_certs: yes
  register: existing_repositories
  tags:
    - validation

- name: "Validate required repositories exist"
  set_fact:
    available_repositories: "{{ existing_repositories.json.results | map(attribute='name') | list }}"
  tags:
    - validation

- name: "Check for missing repositories"
  debug:
    msg: "Missing repository: {{ item }}"
  loop: "{{ content_views | subelements('repositories') | map(attribute='1') | list | unique }}"
  when:
    - item not in available_repositories
    - validate_content_views | bool
  tags:
    - validation

- name: "Display validation summary"
  debug:
    msg:
      - "Satellite Server: {{ satellite_server_url }} - OK"
      - "Organization: {{ satellite_organization }} (ID: {{ organization_id }})"
      - "Available Repositories: {{ available_repositories | length }}"
      - "Lifecycle Environments to Create: {{ lifecycle_environments | length }}"
      - "Content Views to Create: {{ content_views | length }}"
      - "Composite Views to Create: {{ composite_content_views | length }}"
      - "Activation Keys to Create: {{ activation_keys | length }}"
  when: debug_mode | bool
  tags:
    - validation
