---
- name: Red Hat Satellite Quick Demo Setup
  hosts: localhost
  gather_facts: false
  vars:
    # Demo Satellite credentials
    satellite_server_url: "https://satellite.example.com"
    satellite_username: "admin"
    satellite_password: "NTY4NjIw" # Demo default password
    satellite_organization: "Default Organization"
    satellite_location: "Default Location"

  tasks:
    - name: Display demo credentials and setup information
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - " Red Hat Satellite Demo Setup"
          - "=========================================="
          - ""
          - "Default Demo Credentials:"
          - " Username: {{ satellite_username }}"
          - " Password: {{ satellite_password }}"
          - " Server URL: {{ satellite_server_url }}"
          - " Organization: {{ satellite_organization }}"
          - " Location: {{ satellite_location }}"
          - ""
          - "Quick Start Commands:"
          - ""
          - "1. Run complete demo:"
          - " ansible-playbook -i inventory_demo satellite_complete_demo.yml"
          - ""
          - "2. Use demo variables:"
          - " ansible-playbook -i inventory_demo -e @group_vars/satellite_demo.yml satellite_complete_demo.yml"
          - ""
          - "3. Test connectivity:"
          - " ansible-playbook -i inventory_demo satellite_quick_demo.yml"
          - ""
          - "4. Custom demo with different credentials:"
          - " ansible-playbook -i inventory_demo \\"
          - " -e satellite_server_url='https://your-satellite.com' \\"
          - " -e satellite_username='admin' \\"
          - " -e satellite_password='your_password' \\"
          - " satellite_complete_demo.yml"
          - ""
          - "=========================================="
          - "WARNING: Demo credentials only!"
          - "Do NOT use 'NTY4NjIw' in production!"
          - "=========================================="

    - name: Test Satellite connectivity (if server is available)
      ansible.builtin.uri:
        url: "{{ satellite_server_url }}/api/v2/ping"
        method: GET
        user: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        force_basic_auth: true
        validate_certs: false
        timeout: 10
      register: satellite_ping
      failed_when: false
      ignore_errors: true

    - name: Display connection test results
      ansible.builtin.debug:
        msg:
          - "Satellite Connection Test:"
          - " Server: {{ satellite_server_url }}"
          - " Status: {{ 'SUCCESS - Server is reachable' if satellite_ping.status == 200 else 'FAILED - Server unreachable or credentials invalid' }}"
          - " Response Code: {{ satellite_ping.status | default('No response') }}"
          - ""
          - "{% if satellite_ping.status == 200 %}Next Steps: Run full demo playbooks{% else %}Next Steps: Verify server URL and credentials{% endif %}"

    - name: Create demo reports directory
      ansible.builtin.file:
        path: "./demo_reports"
        state: directory
        mode: '0755'

    - name: Generate demo credential reference file
      ansible.builtin.copy:
        content: |
          # Red Hat Satellite Demo Credentials Reference

          ## Demo Environment Access

          ### Satellite Server
          - **URL**: {{ satellite_server_url }}
          - **Username**: {{ satellite_username }}
          - **Password**: {{ satellite_password }}
          - **Organization**: {{ satellite_organization }}
          - **Location**: {{ satellite_location }}

          ### Web Interface Access
          1. Open browser to: {{ satellite_server_url }}
          2. Login with username: `{{ satellite_username }}`
          3. Login with password: `{{ satellite_password }}`

          ### Command Line Access
          ```bash
          # Test API connectivity
          curl -k -u "{{ satellite_username }}:{{ satellite_password }}" \
            "{{ satellite_server_url }}/api/v2/ping"

          # Hammer CLI commands
          hammer auth login basic \
            --username {{ satellite_username }} \
            --password {{ satellite_password }}

          # List organizations
          hammer organization list

          # List hosts
          hammer host list
          ```

          ### Ansible Integration
          ```yaml
          # Use in playbooks
          satellite_server_url: "{{ satellite_server_url }}"
          satellite_username: "{{ satellite_username }}"
          satellite_password: "{{ satellite_password }}"
          satellite_organization: "{{ satellite_organization }}"
          ```

          ### Demo Playbook Commands
          ```bash
          # Quick demo setup
          ansible-playbook -i inventory_demo satellite_quick_demo.yml

          # Complete demo
          ansible-playbook -i inventory_demo satellite_complete_demo.yml

          # With custom variables
          ansible-playbook -i inventory_demo \
            -e @group_vars/satellite_demo.yml \
            satellite_complete_demo.yml
          ```

          ## Security Warning

          **[WARNING] IMPORTANT**: These are DEMO credentials only!

          - **Username**: `admin` (standard Satellite admin)
          - **Password**: `NTY4NjIw` (demo default - NOT for production)

          ### For Production Use:
          1. Change default passwords immediately
          2. Use Ansible Vault for credential storage
          3. Implement proper certificate validation
          4. Follow Red Hat security best practices
          5. Use organization-specific authentication

          ### Ansible Vault Usage:
          ```bash
          # Create vault file
          ansible-vault create group_vars/all/vault.yml

          # Add to vault.yml:
          vault_satellite_password: "your_secure_password"

          # Use in playbooks:
          satellite_password: "{{ vault_satellite_password }}"

          # Run with vault
          ansible-playbook --ask-vault-pass satellite_complete_demo.yml
          ```

          ---
          Generated: {{ ansible_date_time.iso8601 }}
          Demo Environment: Red Hat Satellite 6.17 with Ansible Automation Platform 2.5
        dest: "./demo_reports/DEMO_CREDENTIALS.md"
        mode: '0644'

    - name: Final demo setup summary
      ansible.builtin.debug:
        msg:
          - "Demo setup completed successfully!"
          - ""
          - "Files created:"
          - " - group_vars/satellite_demo.yml (demo variables)"
          - " - inventory_demo (demo inventory)"
          - " - demo_reports/DEMO_CREDENTIALS.md (credential reference)"
          - ""
          - "Ready to run:"
          - " ansible-playbook -i inventory_demo satellite_complete_demo.yml"
          - ""
          - "Demo credentials: admin / NTY4NjIw"
