---
kpatch_action: install
kpatch_auto_install_patches: true
kpatch_backup_before_install: true
kpatch_check_certificates: true
kpatch_cleanup_old_patches: false
kpatch_emergency_disable: false
kpatch_enable_repos: []
kpatch_force_install: false
kpatch_install_delay: 5
kpatch_install_from_repos: true
kpatch_install_retries: 3
kpatch_install_timeout: 300
kpatch_keep_patches_count: 3
kpatch_log_patches: true
kpatch_notify_handlers: true
kpatch_package_manager: auto
kpatch_patch_list: []
kpatch_report_status: true
kpatch_require_signature: true
kpatch_rhel7_compat: true
kpatch_rhel8_features: true
kpatch_rhel9_features: true
kpatch_service_enabled: true
kpatch_service_state: started
kpatch_set_facts: true
kpatch_skip_validation: false
kpatch_specific_kernel: '{{ ansible_facts[''kernel''] }}'
kpatch_validate_architecture: true
kpatch_validate_kernel: true
kpatch_validate_subscription: true
kpatch_verbose_output: true
kpatch_verification_delay: 5
kpatch_verification_retries: 12
kpatch_verification_timeout: 60
kpatch_verify_patches: true