---
# Modern kpatch-rhel role for live kernel patching on RHEL 7, 8, 9, 10

- name: Include pre-patch validation tasks
  ansible.builtin.include_tasks: validate_system.yml

- name: Include kpatch installation tasks
  ansible.builtin.include_tasks: install_kpatch.yml

- name: Include patch management tasks
  ansible.builtin.include_tasks: manage_patches.yml
  when: kpatch_action in ['install', 'enable', 'disable', 'list']

- name: Include patch verification tasks
  ansible.builtin.include_tasks: verify_patches.yml
  when: kpatch_verify_patches | bool

- name: Include cleanup tasks
  ansible.builtin.include_tasks: cleanup.yml
  when: kpatch_cleanup_old_patches | bool
