---
galaxy_info:
  author: "Unknown"
  description: "Ansible role"
  company: ""
  license: "MIT"
  min_ansible_version: "2.1"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
  galaxy_tags: []

dependencies: []