yum_config_file: "{{ '/etc/yum.conf' if ansible_facts['distribution_major_version']|int < 8 else '/etc/dnf/dnf.conf' }}"
yum_backup_original: true
yum_validate_config: true

yum_rhel_supported_versions:
  - '7'
  - '8'
  - '9'
  - '10'

yum_keepcache: 0
yum_debuglevel: 2
yum_exactarch: 1
yum_obsoletes: 1
yum_gpgcheck: 1
yum_plugins: 1
yum_skip_if_unavailable: 1
yum_installonly_limit: "{{ 5 if ansible_facts['distribution_major_version']|int >= 10 else 3 }}"
yum_timeout: "{{ 600 if ansible_facts['distribution_major_version']|int >= 9 else 300 }}"
yum_minrate: 1
yum_best: "{{ 1 if ansible_facts['distribution_major_version']|int >= 8 else omit }}"
yum_clean_requirements_on_remove: "{{ 1 if ansible_facts['distribution_major_version']|int >= 8 else omit }}"
yum_zchunk: "{{ 1 if ansible_facts['distribution_major_version']|int >= 9 else omit }}"
yum_countme: "{{ 1 if ansible_facts['distribution_major_version']|int >= 9 else omit }}"
yum_fastestmirror: "{{ 1 if ansible_facts['distribution_major_version']|int >= 9 else omit }}"
yum_module_hotfixes: "{{ 1 if ansible_facts['distribution_major_version']|int >= 10 else omit }}"
yum_protect_running_kernel: "{{ 1 if ansible_facts['distribution_major_version']|int >= 10 else omit }}"
yum_localpkg_gpgcheck: "{{ 1 if ansible_facts['distribution_major_version']|int >= 8 else omit }}"
yum_repo_gpgcheck: "{{ 0 if ansible_facts['distribution_major_version']|int >= 8 else omit }}"
yum_enable_automatic_updates: false
yum_restart_services_on_change: true
