---
register_rhel_auto_attach: true
register_rhel_configure_repos: true
register_rhel_force: false
register_rhel_install_satellite_ca: true
register_rhel_install_satellite_tools: false
register_rhel_type: cdn
register_rhel_update_cache: true
register_rhel_use_default_repos: true
register_rhel_validate_certs: true
register_rhel_verbose: true