---
# Modern vulnerability scanning and remediation for RHEL 7, 8, 9, 10

- name: Include system preparation tasks
  ansible.builtin.include_tasks: prepare_system.yml
  when: vulner_scan_enabled | bool

- name: Include vulnerability scanning tasks
  ansible.builtin.include_tasks: scan_vulnerabilities.yml
  when: vulner_scan_enabled | bool

- name: Include remediation tasks
  ansible.builtin.include_tasks: remediate_vulnerabilities.yml
  when: 
    - vulner_scan_enabled | bool
    - vulner_auto_remediate | bool

- name: Include reporting tasks
  ansible.builtin.include_tasks: generate_reports.yml
  when: 
    - vulner_scan_enabled | bool
    - vulner_generate_report | bool