---
patch_pkg_manager: apk
patch_network_service: networking
patch_ssh_service: sshd
patch_firewall_service: iptables
patch_logging_service: syslog

patch_critical_services: []
patch_exclude_packages: []
patch_kernel_packages: []

patch_security_update_cmd: apk upgrade
patch_full_update_cmd: apk upgrade
patch_apk_options: []

patch_alpine_configs:
  repositories: null
  path: /etc/apk/repositories
  backup: true

patch_alpine_branches: []
patch_maintenance_cmds: []
patch_security_repos: []

patch_verify_cmd: apk info --installed
patch_init_system: openrc

patch_openrc_services:
  start_cmd: rc-service
  enable_cmd: rc-update add
  disable_cmd: rc-update del