---
patch_pkg_manager: pacman
patch_network_service: NetworkManager
patch_ssh_service: sshd
patch_firewall_service: iptables
patch_logging_service: systemd-journald

patch_critical_services: []
patch_exclude_packages: []
patch_kernel_packages: []

patch_security_update_cmd: "pacman -Syu --noconfirm"
patch_full_update_cmd: "pacman -Syu --noconfirm"

patch_pacman_options: []
patch_aur_helpers: []
patch_arch_configs: []

pacman_conf: null
path: /etc/makepkg.conf
backup: true
makepkg_conf: null

patch_maintenance_cmds: []
patch_mirror_countries: []
patch_verify_cmd: "pacman -Dk"