---
patch_pkg_manager: portage
patch_network_service: NetworkManager
patch_ssh_service: sshd
patch_firewall_service: iptables
patch_logging_service: syslog-ng

patch_critical_services: []
patch_exclude_packages: []
patch_kernel_packages: []

patch_security_update_cmd: "emerge --update --deep --with-bdeps=y @world"
patch_full_update_cmd: "emerge --sync && emerge --update --deep --with-bdeps=y @world"

patch_emerge_options: []
patch_gentoo_configs:
  make_conf: null
  path: /var/lib/portage/world
  backup: true
  world_file: null

patch_sync_commands: []
patch_maintenance_cmds: []
patch_verify_cmd: "emerge --check-world"
patch_security_use_flags: []
patch_world_update_options: []
patch_kernel_rebuild_indicators: []

patch_emerge_cmds:
  sync: "emerge --sync"
  update_world: "emerge --update --deep --with-bdeps=y @world"
  clean: "emerge --depclean --ask=n"
  rebuild: "revdep-rebuild"