patch_pkg_manager: "{% if ansible_distribution_major_version | int >= 8 %} dnf {% else %} yum {% endif %}"
patch_network_service: NetworkManager
patch_ssh_service: sshd
patch_firewall_service: "{% if ansible_distribution_major_version | int >= 7 %} firewalld {% else %} iptables {% endif %}"
patch_logging_service: rsyslog

patch_critical_services:
  - sshd
  - systemd-logind
  - NetworkManager
  - firewalld

patch_exclude_packages:
  - kernel*
  - dracut*

patch_kernel_packages:
  - kernel
  - kernel-core
  - kernel-modules
  - kernel-devel

patch_security_update_cmd: "{% if patch_pkg_manager == 'dnf' %} dnf update -y --security {% else %} yum update -y --security {% endif %}"
patch_full_update_cmd: "{% if patch_pkg_manager == 'dnf' %} dnf update -y {% else %} yum update -y {% endif %}"

patch_repos_to_enable: []
patch_repos_to_disable: []

patch_rhn_commands:
  register: subscription-manager register
  unregister: subscription-manager unregister
  refresh: subscription-manager refresh

patch_rhel_optimizations:
  '7':
    - name: Enable security updates
      set: dnf config-manager --enable rhel-10-baseos-security
  '8':
    - name: Enable AppStream security
  '9':
    - name: Enable security repository
  '10':
    - name: Enable modern security updates
