patch_pkg_manager: zypper
patch_network_service: NetworkManager
patch_ssh_service: sshd
patch_firewall_service: >-
  {% if ansible_distribution_major_version | int >= 15 %}
  firewalld
  {% else %}
  SuSEfirewall2
  {% endif %}
patch_logging_service: rsyslog
patch_critical_services:
  - sshd
  - systemd-logind
  - NetworkManager
  - firewalld
patch_exclude_packages:
  - kernel-*
  - dracut*
patch_kernel_packages:
  - kernel-default
  - kernel-source
  - kernel-devel
patch_security_update_cmd: zypper patch --category security -y
patch_full_update_cmd: zypper update -y
patch_zypper_options:
  - --non-interactive
  - --auto-agree-with-licenses
  - --no-recommends
patch_security_repos:
  openSUSE:
    - repo-update
    - repo-security
  SLES:
    - SLES{{ ansible_distribution_major_version }}-Security-Pool
patch_opensuse_optimizations:
  '15.4':
    - name: Enable security updates
      repo: zypper addrepo --refresh http://download.opensuse.org/update/leap/15.6/oss/
      security: true
  '15.5':
    - name: Enable security updates
      security: true
  '15.6':
    - name: Enable security updates
      security: true
patch_sles_optimizations:
  '15':
    - name: Enable SLES security updates
      repo: zypper addrepo --refresh https://updates.suse.com/SUSE/Updates/SLE-SERVER/15/x86_64/update/
      security: true
patch_maintenance_cmds:
  - zypper clean --all
  - zypper verify
patch_lock_packages: []
patch_unlock_packages: []
