---
# Red Hat Satellite Repository Management Role - Default Variables
# Compatible with: Red Hat Satellite 6.17 on RHEL 9
# Author: sgallego
# Version: 2.0.0
# Date: 2025-08-27

# Satellite server configuration
satellite_server_url: "{{ ansible_fqdn }}"
satellite_username: "admin"
satellite_password: "{{ satellite_admin_password | default('redhat') }}"
satellite_organization: "Red_Hat"
satellite_location: "Denver"

# Red Hat Subscription Management
redhat_username: "{{ rhn_username }}"
redhat_password: "{{ rhn_password }}"
redhat_activation_key: "{{ rhn_activation_key | default('') }}"

# RHEL 9 Product and Repository Configuration
rhel_version: "9"
rhel_architecture: "x86_64"

# Products to enable
satellite_products:
  - name: "Red Hat Enterprise Linux for x86_64"
    label: "rhel-9-for-x86_64"
    repositories:
      - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)"
        label: "rhel-9-for-x86_64-appstream-rpms"
        releasever: "9"
        basearch: "x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)"
        label: "rhel-9-for-x86_64-baseos-rpms"
        releasever: "9"
        basearch: "x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - Supplementary (RPMs)"
        label: "rhel-9-for-x86_64-supplementary-rpms"
        releasever: "9"
        basearch: "x86_64"
  
  - name: "Red Hat Satellite"
    label: "satellite-6.17"
    repositories:
      - name: "Red Hat Satellite 6.17 for RHEL 9 x86_64 (RPMs)"
        label: "satellite-6.17-for-rhel-9-x86_64-rpms"
        releasever: "9"
        basearch: "x86_64"
      - name: "Red Hat Satellite Maintenance 6.17 for RHEL 9 x86_64 (RPMs)"
        label: "satellite-maintenance-6.17-for-rhel-9-x86_64-rpms"
        releasever: "9"
        basearch: "x86_64"

# Repository synchronization settings
repo_sync_immediate: true
repo_download_policy: "immediate"  # immediate, on_demand, background
repo_mirror_on_sync: true
repo_verify_ssl: true

# Sync plan configuration
sync_plans:
  - name: "RHEL_9_Daily_Sync"
    description: "Daily sync plan for RHEL 9 repositories"
    interval: "daily"
    sync_date: "{{ ansible_date_time.date }} 02:00:00 UTC"
    enabled: true
    products: "{{ satellite_products | map(attribute='name') | list }}"

  - name: "RHEL_9_Weekly_Sync"
    description: "Weekly sync plan for RHEL 9 repositories"
    interval: "weekly"
    sync_date: "{{ ansible_date_time.date }} 03:00:00 UTC"
    cron_expression: "0 3 * * 0"
    enabled: false
    products: "{{ satellite_products | map(attribute='name') | list }}"

# Repository set enablement
enable_all_repositories: true
disable_unused_repositories: false

# Validation settings
validate_repo_sync: true
sync_timeout: 7200  # 2 hours in seconds
max_concurrent_syncs: 5

# Logging and reporting
enable_detailed_logging: true
generate_sync_reports: true
email_sync_reports: false
email_recipients: []

# Advanced repository settings
repo_ssl_ca_cert: ""
repo_ssl_client_cert: ""
repo_ssl_client_key: ""
repo_gpg_key: ""
repo_unprotected: false
repo_checksum_type: "sha256"

# Cleanup settings
cleanup_old_packages: false
cleanup_retention_days: 30
orphan_cleanup: false

# Performance tuning
pulp_workers: 4
sync_batch_size: 100
metadata_expire: 86400  # 24 hours

# Debugging and development
debug_mode: false
dry_run: false
force_sync: false
skip_repo_validation: false
