---
# Red Hat Satellite Host Management - Default Variables
# Compatible with: Red Hat Satellite 6.17 on RHEL 9
# Author: sgallego
# Version: 2.0.0
# Date: 2025-08-27

# Satellite server configuration
satellite_server_url: "{{ ansible_fqdn }}"
satellite_username: "admin"
satellite_password: "{{ satellite_admin_password | default('redhat') }}"
satellite_organization: "Red_Hat"
satellite_location: "Denver"

# Host registration and management
host_registration:
  activation_key: ""  # Will be set based on operation
  force_registration: false
  update_packages_on_registration: true
  install_katello_agent: true
  
host_management_operations:
  enable_remote_execution: true
  enable_insights: true
  enable_rhc: true
  configure_satellite_tools: true

# Target host configuration
target_hosts:
  single_node:
    hostname: ""
    ip_address: ""
    activation_key: ""
    host_collection: ""
    
  host_groups: []
  # Example:
  # - name: "Web Servers"
  #   activation_key: "RHEL_9_PROD_AK"
  #   host_pattern: "web*.example.com"
  #   host_collection: "RHEL_9_PROD_Servers"
    
  all_nodes:
    activation_key: "RHEL_9_PROD_AK"
    host_collection: "RHEL_9_PROD_Servers"
    exclude_patterns: []

# Package update operations
package_operations:
  cve_updates:
    enabled: true
    target_cves: 
      - "CVE-2024-6387"  # OpenSSH regreSSHion
      - "CVE-2024-1086"  # Universal LPE
      - "CVE-2023-4911"  # Looney Tunables
      - "CVE-2023-32629" # GStreamer
      - "CVE-2023-2002"  # Bluetooth
    auto_reboot_if_needed: false
    
  security_updates:
    enabled: true
    auto_install: false
    exclude_packages: []
    reboot_if_kernel_updated: false
    
  bugfix_updates:
    enabled: true
    auto_install: false
    exclude_packages: []
    
  all_updates:
    enabled: false
    auto_install: false
    exclude_packages: []
    reboot_if_kernel_updated: true

# Remote Execution Configuration
remote_execution:
  ssh_user: "root"
  ssh_key_path: "/var/lib/foreman-proxy/.ssh/id_rsa_foreman_proxy"
  sudo_password: ""
  connection_timeout: 120
  execution_timeout: 3600
  
# Red Hat Insights Configuration  
insights_config:
  auto_register: true
  collect_insights: true
  upload_frequency: "weekly"
  tags: 
    - "satellite-managed"
    - "rhel-9"
  display_name_template: "{{ ansible_hostname }}.{{ ansible_domain | default('localdomain') }}"

# Red Hat Connector (RHC) Configuration
rhc_config:
  auto_connect: true
  activation_key: ""  # Will inherit from host activation key
  insights_tags: 
    - "rhc-enabled"
    - "satellite-connected"
  
# Host collection management
host_collection_operations:
  auto_add_new_hosts: true
  remove_hosts_on_unregister: true
  bulk_actions_enabled: true
  
# Update job configuration
update_jobs:
  job_template: "Package Action - Katello Script Default"
  timeout: 3600  # 1 hour
  concurrency_level: 5
  batch_size: 10
  max_retries: 3
  
# Compliance and monitoring
compliance_settings:
  enable_openscap: false
  compliance_policy: ""
  scan_schedule: "weekly"
  
monitoring_settings:
  collect_facts: true
  fact_collection_interval: "daily"
  performance_monitoring: false

# Advanced host management
advanced_settings:
  auto_unregister_missing_hosts: false
  missing_host_threshold_days: 30
  cleanup_old_reports: true
  report_retention_days: 90
  
# Debugging and validation
debug_mode: false
dry_run: false
validate_host_operations: true
generate_reports: true
email_reports: false
email_recipients: []

# Bulk operations
bulk_operations:
  enabled: false
  operation_type: "register"  # register, update, unregister
  target_pattern: "*"
  exclude_patterns: []
  max_concurrent_operations: 10
