---
# Repository configuration tasks

- name: Include version-specific repository variables
  include_vars: "rhel{{ ansible_distribution_major_version }}_repos.yml"
  when: register_rhel_use_default_repos | default(true)

- name: Enable default repositories for RHEL version
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ default_repos | default([]) }}"
  when: 
    - register_rhel_use_default_repos | default(true)
    - default_repos is defined
  ignore_errors: true

- name: Enable custom repositories if specified
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ register_rhel_additional_repos | default([]) }}"
  when: register_rhel_additional_repos is defined
  ignore_errors: true

- name: Disable unwanted repositories if specified
  rhsm_repository:
    name: "{{ item }}"
    state: disabled
  loop: "{{ register_rhel_disable_repos | default([]) }}"
  when: register_rhel_disable_repos is defined
  ignore_errors: true

- name: Update package cache after repository configuration
  package:
    update_cache: true
  when: register_rhel_update_cache | default(true)

- name: Display enabled repositories
  command: subscription-manager repos --list-enabled
  register: enabled_repos
  changed_when: false
  when: register_rhel_verbose | default(true)

- name: Show enabled repositories
  debug:
    msg: |
      Currently enabled repositories:
      {{ enabled_repos.stdout }}
  when: 
    - register_rhel_verbose | default(true)
    - enabled_repos is defined
