---
vulner_scan_enabled: true
vulner_auto_remediate: false
vulner_scan_depth: comprehensive
vulner_max_vulnerabilities: 10
vulner_severity_threshold: medium
vulner_use_redhat_oval: true
vulner_use_cve_database: true
vulner_use_security_advisories: true
vulner_use_package_auditor: true
vulner_priority_cves:
vulner_critical_packages:
vulner_remediate_packages: true
vulner_remediate_configs: true
vulner_remediate_services: true
vulner_create_backups: true
vulner_test_after_fix: true
vulner_install_tools: true
vulner_update_definitions: true
vulner_tools_list:
vulner_generate_report: true
vulner_report_format: html
vulner_report_path: /tmp/vulnerability_report_{{ ansible_date_time.epoch }}
vulner_include_remediation: true
vulner_send_notifications: false
vulner_emergency_mode: false
vulner_allow_reboots: false
vulner_maintenance_window: false
vulner_rollback_on_failure: true
vulner_compliance_mode: false
vulner_audit_logging: true
vulner_retain_logs_days: 30
vulner_parallel_processing: true
vulner_timeout_seconds: 600
vulner_retry_count: 3
vulner_skip_running_kernel: false