---
'10': null
'7': null
'8': null
'9': null
appstream: rhel-10-for-x86_64-appstream-rpms
base: rhel-7-server-rpms
baseos: rhel-10-for-x86_64-baseos-rpms
color: '#059669'
critical: null
description: Optional updates or compliant systems
detailed: d-abcdef1234567890abcdef1234567890
detailed_report: null
email_templates: null
executive: d-1234567890abcdef1234567890abcdef
executive_summary: null
extras: rhel-7-server-extras-rpms
high: null
icon: ''
low: null
medium: null
optional: rhel-7-server-optional-rpms
package_manager: dnf
priority: high
repo_command: dnf repolist
report_severity_levels: null
rhel_repos: null
rhel_version_config: null
security: rhel-10-for-x86_64-baseos-rpms
security_alert: null
security_check_cmd: dnf updateinfo list sec
security_plugin: dnf
sendgrid_template_mappings: null
subject: '[URGENT] Security Updates Required - RHEL Fleet'
subscription_check: subscription-manager status
support_status: Full Support
update_check_cmd: dnf check-update